[package]
name = "brokerage-messages"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Messages for communicating between a brokerage server and client"
repository = "https://github.com/tfiala/brokerage-messages-rs"

[dependencies]

[dev-dependencies]
version-sync = "0.9.5"

